/* Generated by tools/generate_cursor_easing.js. */
#ifndef CURSOR_EASING_H
#define CURSOR_EASING_H

#define CURSOR_EASING_NUMERATOR 3u
#define CURSOR_EASING_DENOMINATOR 16u
#define CURSOR_EASING_MAX_INDEX 320u
#define CURSOR_EASING_MIN_STEP 8u

#endif /* CURSOR_EASING_H */
