/*
 * Ordered dither demo.
 *
 * Animates a 16x16 sprite dissolving in and out using dithered transparency
 * driven by a precomputed 16x16 ordered dither matrix.  Comparing each
 * pixel's dither rank against a rotating threshold produces a smooth
 * dissolve animation.
 *
 * Rather than re-evaluating every pixel each frame, an inverted lookup
 * table and head/tail pointers index directly into the pixels that cross the
 * threshold. A spatial offset applied every 256 steps lengthens the cycle.
 *
 * Build (GBDK-2020):
 *   lcc -DNDEBUG -Wf--opt-code-speed -Wf--max-allocs-per-node50000 -o
 * dither_demo.gb dither_demo.c
 */

#include <gb/gb.h>
#include <gb/hardware.h>
#include <gbdk/console.h>
#include <gbdk/font.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#define WRAP_STEP 213 /* Spatial offset per 256-step cycle: 13*16 + 5 */
#define MAX_SPEED 64  /* Maximum pixel updates per frame */

#define SPR_TILE 130 /* Sprite tile start index */
#define BG_TILE 128  /* Background tile start index */
#define WRAP_X 168   /* 160 + OAM x-offset 8 */
#define WRAP_Y 160   /* 144 + OAM y-offset 16 */
#define WRAP(v, lim) ((v) >= (lim) ? (v) - (lim) : (v))
#define DPAD (J_LEFT | J_RIGHT | J_UP | J_DOWN)

const __at(0x2100) uint8_t _mushroom_rom[64] = {
    7,   7,   30,  25,  62,  33, 124, 67,  121, 70,  131, 252, 179,
    204, 251, 132, 224, 224, 24, 248, 28,  228, 14,  242, 230, 26,
    241, 15,  241, 15,  243, 13, 249, 134, 176, 207, 143, 255, 127,
    114, 63,  34,  63,  32,  31, 16,  15,  15,  231, 25,  7,   249,
    243, 253, 254, 78,  252, 68, 252, 4,   248, 8,   240, 240,
};
#define mushroom ((const uint8_t *)0x2100u)

/* pos_lut[fill_order] = linear pixel index (0..255).
 * Generated by void-and-cluster (sigma=1.7, seed=184).
 * 256-byte aligned so the high byte is constant for all lookups. */
const __at(0x2000) uint8_t _pos_lut_rom[256] = {
    106, 17,  147, 220, 230, 96,  27,  38,  208, 102, 158, 166, 77,  171, 83,
    211, 217, 57,  31,  4,   137, 177, 8,   253, 125, 51,  184, 129, 79,  87,
    190, 133, 241, 197, 59,  250, 139, 37,  65,  238, 115, 186, 45,  179, 247,
    135, 143, 72,  243, 92,  189, 68,  199, 32,  251, 176, 40,  121, 255, 111,
    164, 244, 203, 101, 124, 28,  34,  145, 168, 248, 209, 74,  98,  54,  62,
    213, 173, 134, 222, 19,  25,  218, 110, 105, 15,  195, 154, 6,   114, 160,
    64,  183, 86,  12,  75,  225, 148, 141, 52,  216, 221, 46,  41,  136, 2,
    82,  229, 144, 187, 108, 22,  165, 88,  234, 192, 49,  100, 14,  155, 127,
    43,  196, 242, 232, 78,  152, 70,  206, 146, 21,  90,  252, 117, 157, 33,
    24,  194, 185, 97,  214, 240, 76,  120, 10,  204, 36,  149, 159, 30,  123,
    71,  95,  228, 162, 67,  223, 200, 42,  7,   116, 235, 1,   156, 182, 93,
    113, 104, 191, 48,  169, 210, 29,  5,   69,  56,  237, 163, 233, 126, 151,
    18,  91,  188, 99,  212, 44,  138, 239, 231, 128, 50,  118, 39,  63,  174,
    26,  181, 202, 193, 3,   89,  131, 109, 254, 81,  53,  246, 153, 219, 0,
    60,  161, 103, 9,   140, 198, 226, 84,  150, 80,  205, 73,  20,  47,  11,
    175, 201, 107, 130, 23,  180, 224, 170, 94,  85,  13,  245, 142, 35,  119,
    58,  215, 178, 236, 16,  172, 132, 112, 122, 55,  227, 61,  249, 167, 207,
    66,
};
#define pos_lut ((const uint8_t *)0x2000u)

const __at(0x2200) uint8_t _bit_mask_rom[8] = {0x80, 0x40, 0x20, 0x10,
                                               0x08, 0x04, 0x02, 0x01};
#define bit_mask ((const uint8_t *)0x2200u)

static const uint8_t bg_tiles[32] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF,
    0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF,
};

/* Dithering state */
static uint8_t head, tail, head_off, tail_off;
__at(0xC100) uint8_t _spr_buf_mem[64];
#define spr_buf ((uint8_t *)0xC100u)

static uint8_t speed = 4, transparency = 64;
static uint8_t spr_x = 72, spr_y = 64;

/* Head/tail pointers chase through the LUT; gap between them == transparency.
 * When transparency >= 128, swap head/tail so the same loop body handles
 * both halves. */
static void update_sprite_buf(void) {
    uint8_t do_swap = transparency & 0x80;

    if (do_swap) {
        if (head == tail)
            /* Advance head by one step so the swapped gap is 255, not 0.
             * Without this, the clear/restore roles invert at gap 0. */
            if (++head == 0)
                head_off += WRAP_STEP;
        uint8_t tmp = head;
        head = tail;
        tail = tmp;
        tmp = head_off;
        head_off = tail_off;
        tail_off = tmp;
    }

    for (uint8_t n = speed; n--;) {
        uint8_t gap = head - tail;
        if (gap <= transparency) {
            uint8_t idx = pos_lut[head] + head_off;
            uint8_t off = (idx >> 2) & 0x3E;
            uint8_t m = ~bit_mask[idx & 7];
            spr_buf[off] &= m;
            spr_buf[off + 1] &= m;
            if (++head == 0)
                head_off += WRAP_STEP;
        }
        if (gap >= transparency) {
            uint8_t idx = pos_lut[tail] + tail_off;
            uint8_t off = (idx >> 2) & 0x3E;
            uint8_t m = bit_mask[idx & 7];
            spr_buf[off] ^= mushroom[off] & m;
            spr_buf[off + 1] ^= mushroom[off + 1] & m;
            if (++tail == 0)
                tail_off += WRAP_STEP;
        }
    }

    if (do_swap) {
        uint8_t tmp = head;
        head = tail;
        tail = tmp;
        tmp = head_off;
        head_off = tail_off;
        tail_off = tmp;
    }
}

static void put_u8_pad3(uint8_t v) {
    putchar(v < 100 ? ' ' : '0' + v / 100);
    putchar(v < 10 ? ' ' : '0' + v / 10 % 10);
    putchar('0' + v % 10);
}

static void print_status(void) {
    gotoxy(0, 0);
    printf("Transparency ");
    put_u8_pad3(transparency);
    gotoxy(0, 2);
    printf("Speed ");
    put_u8_pad3(speed);
}

void main(void) {
    /* Set up graphics */
    DISPLAY_OFF;
    BGP_REG = OBP0_REG = DMG_PALETTE(0, 1, 2, 3);

    font_init();
    font_load(font_spect);

    set_bkg_data(BG_TILE, 2, bg_tiles);
    uint8_t row[32];
    for (uint8_t y = 0; y < 32; y++) {
        for (uint8_t x = 0; x < 32; x++)
            row[x] = BG_TILE + ((x + y) & 1);
        set_bkg_tiles(0, y, 32, 1, row);
    }

    print_status();
    gotoxy(0, 1);
    printf("Hold A+L/R to change\nHold A+U/D to changeDPAD to move sprites");

    memset(spr_buf, 0, 64);
    set_sprite_data(SPR_TILE, 4, spr_buf);
    for (uint8_t i = 0; i < 4; i++)
        set_sprite_tile(i, SPR_TILE + i);
    move_sprite(0, spr_x + 8, spr_y + 16);
    move_sprite(1, spr_x + 16, spr_y + 16);
    move_sprite(2, spr_x + 8, spr_y + 24);
    move_sprite(3, spr_x + 16, spr_y + 24);

    SHOW_BKG;
    SHOW_SPRITES;
    DISPLAY_ON;

    /* Initialize input state */
    uint8_t cur = 0, rep_timer = 0;

    while (1) {
        vsync();

        /* Copy the sprite buffer during vblank */
        set_sprite_data(SPR_TILE, 4, spr_buf);

        /* Apply the dissolve animation */
        update_sprite_buf();

        /* Handle input */
        uint8_t prev = cur;
        cur = joypad();
        uint8_t repeated = 0;
        uint8_t held = cur & DPAD;
        if (held && held == (prev & DPAD)) {
            if (++rep_timer == 25) {
                repeated = held;
                rep_timer = 21;
            }
        } else
            rep_timer = 0;
        if (cur & J_A) {
            uint8_t action = (cur & ~prev) | repeated;
            if (action & J_RIGHT)
                transparency++;
            if (action & J_LEFT)
                transparency--;
            if (action & J_UP)
                speed = (speed >= MAX_SPEED) ? 0 : speed + 1;
            if (action & J_DOWN)
                speed = (speed == 0) ? MAX_SPEED : speed - 1;
            if (action & DPAD)
                print_status();
        } else {
            if (cur & J_UP)
                spr_y = (spr_y == 0) ? WRAP_Y - 1 : spr_y - 1;
            if (cur & J_DOWN)
                spr_y = WRAP(spr_y + 1, WRAP_Y);
            if (cur & J_LEFT)
                spr_x = (spr_x == 0) ? WRAP_X - 1 : spr_x - 1;
            if (cur & J_RIGHT)
                spr_x = WRAP(spr_x + 1, WRAP_X);
            if (cur & DPAD) {
                uint8_t x0 = WRAP(spr_x + 8, WRAP_X);
                uint8_t x1 = WRAP(spr_x + 16, WRAP_X);
                uint8_t y0 = WRAP(spr_y + 16, WRAP_Y);
                uint8_t y1 = WRAP(spr_y + 24, WRAP_Y);
                move_sprite(0, x0, y0);
                move_sprite(1, x1, y0);
                move_sprite(2, x0, y1);
                move_sprite(3, x1, y1);
            }
        }
    }
}
