const assert = require("assert");
const fs = require("fs");

const BOARD_MARGIN = 1;
const COORD_SHIFT = 5;
const BOARD_SIZES = [9, 13, 19];
const VALUES_PER_LINE = 12;

const SURFACE_CORNER_TL = 0;
const SURFACE_EDGE_T = 1;
const SURFACE_CORNER_TR = 2;
const SURFACE_EDGE_L = 3;
const SURFACE_CENTER = 4;
const SURFACE_EDGE_R = 5;
const SURFACE_CORNER_BL = 6;
const SURFACE_EDGE_B = 7;
const SURFACE_CORNER_BR = 8;
const SURFACE_HOSHI = 9;

function surfaceKind(col, row, size) {
  const last = size - 1;

  if (row === 0) {
    if (col === 0) return SURFACE_CORNER_TL;
    if (col === last) return SURFACE_CORNER_TR;
    return SURFACE_EDGE_T;
  }
  if (row === last) {
    if (col === 0) return SURFACE_CORNER_BL;
    if (col === last) return SURFACE_CORNER_BR;
    return SURFACE_EDGE_B;
  }
  if (col === 0) return SURFACE_EDGE_L;
  if (col === last) return SURFACE_EDGE_R;

  const large = size >= 13;
  const distance = large ? 3 : 2;
  const center = size >> 1;
  const far = last - distance;
  const onCol = col === distance || col === far || col === center;
  const onRow = row === distance || row === far || row === center;

  if (onCol && onRow) {
    if (large || (col === center) === (row === center))
      return SURFACE_HOSHI;
  }
  return SURFACE_CENTER;
}

function packedSurface(size) {
  const lastCoord = (size << COORD_SHIFT) | size;
  const kinds = new Uint8Array(lastCoord + 1);

  for (let row = 0; row < size; row++) {
    for (let col = 0; col < size; col++) {
      const coord =
        ((row + BOARD_MARGIN) << COORD_SHIFT) | (col + BOARD_MARGIN);
      kinds[coord] = surfaceKind(col, row, size);
    }
  }

  const packed = [];
  for (let coord = 0; coord < kinds.length; coord += 2)
    packed.push(kinds[coord] | ((kinds[coord + 1] ?? 0) << 4));
  return packed;
}

function formatArray(size) {
  const packed = packedSurface(size);
  const lines = [];

  for (let index = 0; index < packed.length; index += VALUES_PER_LINE) {
    const values = packed
      .slice(index, index + VALUES_PER_LINE)
      .map((value) => `0x${value.toString(16).padStart(2, "0")}`)
      .join(", ");
    lines.push(`    ${values},`);
  }

  return [
    `static const uint8_t board_surface_${size}[${packed.length}] = {`,
    ...lines,
    "};",
  ].join("\n");
}

const outputPath = process.argv[2];
assert(outputPath, "output header path is required");

const arrays = BOARD_SIZES.map(formatArray).join("\n\n");
const output = `/* Generated by tools/generate_board_surfaces.js. */
#ifndef BOARD_SURFACES_H
#define BOARD_SURFACES_H

#include <stdint.h>

${arrays}

#endif /* BOARD_SURFACES_H */
`;

fs.writeFileSync(outputPath, output);
