const assert = require("assert");
const fs = require("fs");

const BOARD_MARGIN = 1;
const COORD_SHIFT = 5;
const BOARD_SIZES = [9, 13, 19];
const TILEMAP_WIDTH = 1 << COORD_SHIFT;
const TILEMAP_SIZE = TILEMAP_WIDTH * TILEMAP_WIDTH;
const VALUES_PER_LINE = 8;

const SURFACE_CORNER_TL = 0;
const SURFACE_EDGE_T = 1;
const SURFACE_CORNER_TR = 2;
const SURFACE_EDGE_L = 3;
const SURFACE_CENTER = 4;
const SURFACE_EDGE_R = 5;
const SURFACE_CORNER_BL = 6;
const SURFACE_EDGE_B = 7;
const SURFACE_CORNER_BR = 8;
const SURFACE_HOSHI = 9;

const SURFACE_TILES = [
  "TILE_CORNER_TL",
  "TILE_EDGE_T",
  "TILE_CORNER_TR",
  "TILE_EDGE_L",
  "TILE_CENTER",
  "TILE_EDGE_R",
  "TILE_CORNER_BL",
  "TILE_EDGE_B",
  "TILE_CORNER_BR",
  "TILE_HOSHI",
];

function surfaceKind(col, row, size) {
  const last = size - 1;

  if (row === 0) {
    if (col === 0) return SURFACE_CORNER_TL;
    if (col === last) return SURFACE_CORNER_TR;
    return SURFACE_EDGE_T;
  }
  if (row === last) {
    if (col === 0) return SURFACE_CORNER_BL;
    if (col === last) return SURFACE_CORNER_BR;
    return SURFACE_EDGE_B;
  }
  if (col === 0) return SURFACE_EDGE_L;
  if (col === last) return SURFACE_EDGE_R;

  const large = size >= 13;
  const distance = large ? 3 : 2;
  const center = size >> 1;
  const far = last - distance;
  const onCol = col === distance || col === far || col === center;
  const onRow = row === distance || row === far || row === center;

  if (onCol && onRow) {
    if (large || (col === center) === (row === center))
      return SURFACE_HOSHI;
  }
  return SURFACE_CENTER;
}

function tilemap(size) {
  const tiles = new Array(TILEMAP_SIZE).fill("TILE_EMPTY");
  const set = (col, row, tile) => {
    tiles[(row << COORD_SHIFT) | col] = tile;
  };

  set(0, 0, "TILE_FRAME_TL");
  for (let col = 0; col < size; col++)
    set(col + BOARD_MARGIN, 0, "TILE_FRAME_T");
  set(size + BOARD_MARGIN, 0, "TILE_FRAME_TR");

  for (let row = 0; row < size; row++) {
    set(0, row + BOARD_MARGIN, "TILE_FRAME_L");
    for (let col = 0; col < size; col++) {
      set(
        col + BOARD_MARGIN,
        row + BOARD_MARGIN,
        SURFACE_TILES[surfaceKind(col, row, size)],
      );
    }
    set(size + BOARD_MARGIN, row + BOARD_MARGIN, "TILE_FRAME_R");
  }

  const upper = size + BOARD_MARGIN;
  const lower = upper + 1;
  set(0, upper, "TILE_FRAME_BL_U");
  set(0, lower, "TILE_FRAME_BL_D");
  for (let col = 0; col < size; col++) {
    set(col + BOARD_MARGIN, upper, "TILE_FRAME_B_U");
    set(col + BOARD_MARGIN, lower, "TILE_FRAME_B_D");
  }
  set(size + BOARD_MARGIN, upper, "TILE_FRAME_BR_U");
  set(size + BOARD_MARGIN, lower, "TILE_FRAME_BR_D");

  return tiles;
}

function formatArray(size) {
  const tiles = tilemap(size);
  const lines = [];

  for (let index = 0; index < tiles.length; index += VALUES_PER_LINE) {
    const values = tiles
      .slice(index, index + VALUES_PER_LINE)
      .join(", ");
    lines.push(`    ${values},`);
  }

  return [
    `static const uint8_t board_surface_${size}[BOARD_SURFACE_TILEMAP_SIZE] = {`,
    ...lines,
    "};",
  ].join("\n");
}

const outputPath = process.argv[2];
assert(outputPath, "output header path is required");

const arrays = BOARD_SIZES.map(formatArray).join("\n\n");
const output = `/* Generated by tools/generate_board_surfaces.js. */
#ifndef BOARD_SURFACES_H
#define BOARD_SURFACES_H

#include "display.h"

#define BOARD_SURFACE_TILEMAP_SIZE ${TILEMAP_SIZE}u

${arrays}

#endif /* BOARD_SURFACES_H */
`;

fs.writeFileSync(outputPath, output);
