#!/usr/bin/env node

"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const EASING_NUMERATOR = 3;
const EASING_DENOMINATOR = 16;
const SUBPIXELS_PER_PIXEL = 256;
const DISTANCE_QUANTUM_SUBPIXELS = SUBPIXELS_PER_PIXEL / 2;
const MAX_DISTANCE_PIXELS = 160;
const MIN_STEP_SUBPIXELS = 8;
const PAGE_SIZE = 256;
const EXTENSION_OFFSET = 256;
const EXTENSION_HIGH_OFFSET = 128;
const VALUES_PER_LINE = 16;

const tableSize =
  (MAX_DISTANCE_PIXELS * SUBPIXELS_PER_PIXEL) /
    DISTANCE_QUANTUM_SUBPIXELS +
  1;

const steps = Array.from({ length: tableSize }, (_, index) =>
  Math.round(
    (index * DISTANCE_QUANTUM_SUBPIXELS * EASING_NUMERATOR) /
      EASING_DENOMINATOR,
  ),
);

assert(steps.at(-1) <= 0xffff, "cursor easing step exceeds uint16_t");

const formatBytes = (values) => {
  const lines = [];
  for (let index = 0; index < values.length; index += VALUES_PER_LINE) {
    const line = values
      .slice(index, index + VALUES_PER_LINE)
      .map((value) => `0x${value.toString(16).padStart(2, "0")}`)
      .join(", ");
    lines.push(`    .db ${line}`);
  }
  return lines.join("\n");
};

const fractionBuckets = Array.from({ length: PAGE_SIZE }, (_, fraction) => {
  if (fraction < 0x40) return 0;
  if (fraction < 0xc0) return 1;
  return 2;
});

const storedSteps = steps.map((step) => Math.max(step, MIN_STEP_SUBPIXELS));
const normalSteps = storedSteps.slice(0, EXTENSION_OFFSET);
const extensionSteps = storedSteps.slice(EXTENSION_OFFSET);
const extensionLow = extensionSteps.map((step) => step & 0xff);
const extensionHigh = extensionSteps.map((step) => step >> 8);
const extensionPadding = EXTENSION_HIGH_OFFSET - extensionSteps.length;
const extensionPage = [
  ...extensionLow,
  ...Array(extensionPadding).fill(0),
  ...extensionHigh,
  ...Array(extensionPadding).fill(0),
];

assert.strictEqual(normalSteps.length, PAGE_SIZE);
assert.strictEqual(extensionPage.length, PAGE_SIZE);

const headerOutput = `/* Generated by tools/generate_cursor_easing.js. */
#ifndef CURSOR_EASING_H
#define CURSOR_EASING_H

#define CURSOR_EASING_NUMERATOR ${EASING_NUMERATOR}u
#define CURSOR_EASING_DENOMINATOR ${EASING_DENOMINATOR}u
#define CURSOR_EASING_MAX_INDEX ${tableSize - 1}u
#define CURSOR_EASING_MIN_STEP ${MIN_STEP_SUBPIXELS}u

#endif /* CURSOR_EASING_H */
`;

const asmOutput = `; Generated by tools/generate_cursor_easing.js.
.module cursor_easing

.globl _cursor_easing_fraction
.globl _cursor_easing_low
.globl _cursor_easing_high
.globl _cursor_easing_extension

.area _CURSOR_EASING

_cursor_easing_fraction::
${formatBytes(fractionBuckets)}

_cursor_easing_low::
${formatBytes(normalSteps.map((step) => step & 0xff))}

_cursor_easing_high::
${formatBytes(normalSteps.map((step) => step >> 8))}

_cursor_easing_extension::
${formatBytes(extensionPage)}
`;

const outputPath = process.argv[2];
assert(outputPath, "usage: node generate_cursor_easing.js <output.{h,s}>");

const extension = path.extname(outputPath);
assert(extension === ".h" || extension === ".s", "output must be .h or .s");
fs.writeFileSync(outputPath, extension === ".h" ? headerOutput : asmOutput);
